name: easy_permission_handler
description: Permission handler now got very easy to integrate
version: 1.0.0
repository: https://github.com/karanm4797/EasyPermissionHandler
license: MIT

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5

  #Responsive screen UI
  sizer: ^2.0.15

  #Permission Handler
  permission_handler: ^10.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
